name: Build APK

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Install dependencies
      run: cd mobile && npm install
    
    - name: Build APK
      run: cd mobile && npm run build-apk
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Toolencahnt-APK
        path: mobile/android/app/build/outputs/apk/release/app-release.apk
        
